version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install NPM modules
          command: npm i
      - run:
          name: Generate Indexes
          command: npm run eta -- generate:indexes
      - run:
          name: Compile
          command: npm run eta -- compile:server
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - save_cache:
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - helpers
            - lib
            - server
            - appspec.yml
            - package.json
            - package-lock.json
      - run:
          name: Unit Tests
          command: npm run eta -- test:core --reporter=mocha-junit-reporter
          environment:
            MOCHA_FILE: /home/circleci/junit/test-results.xml
      - store_test_results:
          path: /home/circleci/junit
      - store_artifacts:
          path: /home/circleci/junit
  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.10
    steps:
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install aws cli
          command:
            sudo apt-get -y -qq install awscli
      - run:
          name: Setting Signature Version 4 for S3 Request Authentication
          command: aws configure set default.s3.signature_version s3v4
      - run:
          name: Deploy to S3
          command:
            aws --region us-east-1 s3 sync / s3://eta-deployments/eta/${CIRCLE_BRANCH}/ --delete

deployment:
  staging:
    branch: deployments
    codedeploy:
      eta-deployment:
        deployment_group: eta-deployment-group
        deployment_config: CodeDeployDefault.OneAtATime
        # application_root: /
        # region: us-east-1
        # revision_location:
        #   revision_type: S3
        #   s3_location:
        #     bucket: eta-deployments
        #     key_pattern: eta/${CIRCLE_BRANCH}/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - deployments
                - circle-ci
                - dev
                - staging
                - master